# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{contentator}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Craig Partin"]
  s.date = %q{2010-04-07}
  s.description = %q{A lightweight cms that focuses on in place editing.}
  s.email = %q{cpartin@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/application_controller.rb",
     "app/controllers/cms/admin/admin_controller.rb",
     "app/controllers/cms/admin/file_attachments_controller.rb",
     "app/controllers/cms/admin/page_content_blocks_controller.rb",
     "app/controllers/cms/admin/pages_controller.rb",
     "app/controllers/cms/content_controller.rb",
     "app/helpers/application_helper.rb",
     "app/helpers/cms/admin/pages_helper.rb",
     "app/models/file_attachment.rb",
     "app/models/page.rb",
     "app/models/page_content_block.rb",
     "app/views/cms/admin/_admin_toolbar.html.haml",
     "app/views/cms/admin/file_attachments/_form.html.haml",
     "app/views/cms/admin/page_content_blocks/_form.html.haml",
     "app/views/cms/admin/pages/_form.html.haml",
     "app/views/cms/admin/pages/edit.html.haml",
     "app/views/cms/admin/pages/index.html.haml",
     "app/views/cms/admin/pages/new.html.haml",
     "app/views/cms/content/_file_attachment.html.haml",
     "app/views/cms/content/_file_attachments_container.html.haml",
     "app/views/cms/content/_page_content_block.html.haml",
     "app/views/cms/content/_page_content_blocks_container.html.haml",
     "app/views/cms/content/content.html.haml",
     "app/views/cms/content/gallery.html.haml",
     "app/views/cms/content/home.html.haml",
     "app/views/layouts/application.html.haml",
     "app/views/layouts/cms/admin/application.html.haml",
     "config/boot.rb",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/geminstaller.local.yml",
     "config/geminstaller.yml",
     "config/initializers/backtrace_silencers.rb",
     "config/initializers/inflections.rb",
     "config/initializers/mime_types.rb",
     "config/initializers/new_rails_defaults.rb",
     "config/initializers/session_store.rb",
     "config/locales/de.yml",
     "config/locales/en.yml",
     "config/routes.rb",
     "contentator.gemspec",
     "db/migrate/20091002165818_create_pages.rb",
     "db/migrate/20091002211930_create_home_page.rb",
     "db/migrate/20091007222703_create_page_content_blocks.rb",
     "db/migrate/20091029204950_create_file_attachments.rb",
     "lib/contentator.rb",
     "lib/generators/content/content_generator.rb",
     "lib/generators/content/templates/container.rb",
     "lib/generators/content/templates/controller.rb",
     "lib/generators/content/templates/factories.rb",
     "lib/generators/content/templates/form.rb",
     "lib/generators/content/templates/functional_test.rb",
     "lib/generators/content/templates/item.rb",
     "lib/generators/content/templates/migration.rb",
     "lib/generators/content/templates/model.rb",
     "lib/generators/content/templates/unit_test.rb",
     "lib/generators/content/templates/view.rb",
     "lib/template.rb",
     "public/404.html",
     "public/422.html",
     "public/500.html",
     "public/favicon.ico",
     "public/images/admin_standard/content-header-bg.png",
     "public/images/admin_standard/context-arrow.png",
     "public/images/admin_standard/context-bg.png",
     "public/images/admin_standard/crumb-bg-current.gif",
     "public/images/admin_standard/crumb-bg.gif",
     "public/images/admin_standard/crumb-divide-current.gif",
     "public/images/admin_standard/crumb-divide.gif",
     "public/images/admin_standard/drawer-end.png",
     "public/images/admin_standard/drawer-middle.png",
     "public/images/admin_standard/drawer-start.png",
     "public/images/admin_standard/form-error.png",
     "public/images/admin_standard/input-background.gif",
     "public/images/admin_standard/shadow-bottom.png",
     "public/images/admin_standard/shadow-right.png",
     "public/images/admin_standard/subnavigation-bullet-1.png",
     "public/images/admin_standard/subnavigation-bullet-2.png",
     "public/images/admin_standard/tab-active-cap.png",
     "public/images/admin_standard/tab-active.png",
     "public/images/admin_standard/tab-inactive-cap.png",
     "public/images/admin_standard/tab-inactive.png",
     "public/images/blank.gif",
     "public/images/icons/add.png",
     "public/images/icons/cancel.png",
     "public/images/icons/delete.png",
     "public/images/icons/edit.png",
     "public/images/icons/folder.png",
     "public/images/icons/move.png",
     "public/images/rails.png",
     "public/robots.txt",
     "public/stylesheets/admin_standard.css",
     "public/stylesheets/application.css",
     "rails_generators/contentator_files/contentator_files_generator.rb",
     "rails_generators/contentator_files/templates/application.rb",
     "test/factories.rb",
     "test/functional/cms/admin/file_attachments_controller_test.rb",
     "test/functional/cms/admin/page_content_blocks_controller_test.rb",
     "test/functional/cms/admin/pages_controller_test.rb",
     "test/functional/cms/content_controller_test.rb",
     "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/file_attachment_test.rb",
     "test/unit/page_content_block_test.rb",
     "test/unit/page_test.rb"
  ]
  s.homepage = %q{http://github.com/cpartin/contentator}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A lightweight cms that focuses on in place editing.}
  s.test_files = [
    "test/factories.rb",
     "test/functional/cms/admin/file_attachments_controller_test.rb",
     "test/functional/cms/admin/page_content_blocks_controller_test.rb",
     "test/functional/cms/admin/pages_controller_test.rb",
     "test/functional/cms/content_controller_test.rb",
     "test/performance/browsing_test.rb",
     "test/test_helper.rb",
     "test/unit/file_attachment_test.rb",
     "test/unit/page_content_block_test.rb",
     "test/unit/page_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 2.2.6"])
    else
      s.add_dependency(%q<haml>, [">= 2.2.6"])
    end
  else
    s.add_dependency(%q<haml>, [">= 2.2.6"])
  end
end
